=== GargSheetal/computer-repair-servic/src/main/resources/repairservice/xmldata/devices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="devices">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="device" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="device_name"/>
							<xs:element name="device_type">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="device_type_name"/>
										<xs:element name="device_brand">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="brand_name"/>
												</xs:sequence>
												<xs:attribute name="device_brand_id" type="xs:int" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="device_type_id" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="device_id" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== GargSheetal/computer-repair-servic/src/main/resources/repairservice/xmldata/devices.xml
<?xml version="1.0" encoding="UTF-8"?>

<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="devices.xsd">
	<device device_id="1">
		<device_name>iPhone 14</device_name>
		<device_type device_type_id="1">
			<device_type_name>Smartphone</device_type_name>
			<device_brand device_brand_id="1">
				<brand_name>Apple</brand_name>
			</device_brand>
		</device_type>
	</device>
	<device device_id="2">
		<device_name>iPhone 13</device_name>
		<device_type device_type_id="1">
			<device_type_name>Smartphone</device_type_name>
			<device_brand device_brand_id="1">
				<brand_name>Apple</brand_name>
			</device_brand>
		</device_type>
	</device>
	<device device_id="3">
		<device_name>Galaxy S20</device_name>
		<device_type device_type_id="2">
			<device_type_name>Smartphone</device_type_name>
			<device_brand device_brand_id="2">
				<brand_name>Samsung</brand_name>
			</device_brand>
		</device_type>
	</device>
	<device device_id="6">
		<device_name>Pixel 6</device_name>
		<device_type device_type_id="4">
			<device_type_name>tablet</device_type_name>
			<device_brand device_brand_id="1">
				<brand_name>Apple</brand_name>
			</device_brand>
		</device_type>
	</device>	
</devices>
