=== GargSheetal/computer-repair-servic/src/main/resources/repairservice/xmldata/work_requests.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="work_requests">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="work_request" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="created_timestamp" type="xs:dateTime"/>
							<xs:element name="last_updated_timestamp" type="xs:dateTime" minOccurs="0"/>
							<xs:element name="completed_timestamp" type="xs:dateTime" minOccurs="0"/>
							<xs:element name="amount" type="xs:double" minOccurs="0"/>
							<xs:element name="work_request_description" type="xs:string" minOccurs="0"/>
							<xs:element name="work_request_appointment" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="appointment_timestamp" type="xs:dateTime"/>
									</xs:sequence>
									<xs:attribute name="work_request_appointment_id" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="work_request_payment" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="payment_confirmation_number" type="xs:string"/>
										<xs:element name="payement_timestamp" type="xs:dateTime"/>
										<xs:element name="amount" type="xs:double"/>
									</xs:sequence>
									<xs:attribute name="work_request_payment_id" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="work_request_id" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== GargSheetal/computer-repair-servic/src/main/resources/repairservice/xmldata/work_requests.xml
<?xml version="1.0" encoding="UTF-8"?>

<work_requests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="work_requests.xsd">
	<work_request work_request_id="1">
		<created_timestamp>2023-01-23T12:45:56</created_timestamp>
		<last_updated_timestamp>2023-01-25T14:30:40</last_updated_timestamp>
		<completed_timestamp>2023-01-27T11:15:26</completed_timestamp>
		<amount>200.00</amount>	
		<work_request_description>please do screen replacement for my iPhone14. Thanks Mark Shelton</work_request_description>
		<work_request_appointment work_request_appointment_id="1">
			<appointment_timestamp>2023-01-25T16:00:00</appointment_timestamp>
		</work_request_appointment>
		<work_request_payment work_request_payment_id="1">
			<payment_confirmation_number>abc123xyz</payment_confirmation_number>
			<payement_timestamp>2023-01-27T12:00:00</payement_timestamp>
			<amount>200.00</amount>
		</work_request_payment>
	</work_request>
</work_requests>
