=== GargSheetal/computer-repair-servic/src/main/resources/repairshop/xmldata/customers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="customers">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="customer" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="last_name" type="xs:string"/>
							<xs:element name="rest_of_name" type="xs:string" minOccurs="0"/>
							<xs:element name="email" type="xs:string"/>
							<xs:element name="phone" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="customer_id" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== GargSheetal/computer-repair-servic/src/main/resources/repairshop/xmldata/customers.xml
<?xml version="1.0" encoding="UTF-8"?>

<customers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="customers.xsd">
	<customer customer_id="1">
		<last_name>Shelton</last_name>
		<rest_of_name>Mark</rest_of_name>
		<email>ms@gmail.com</email>
		<phone>2345645678</phone>
	</customer>
	<customer customer_id="2">
		<last_name>Potter</last_name>
		<rest_of_name>Harry</rest_of_name>
		<email>hp@gmail.com</email>
		<phone>3456789012</phone>
	</customer>
	<customer customer_id="3">
		<last_name>Parker</last_name>
		<rest_of_name>Peter</rest_of_name>
		<email>pp@gmail.com</email>
		<phone>4567890123</phone>
	</customer>
	<customer customer_id="4">
		<last_name>Jane</last_name>
		<rest_of_name>Mary</rest_of_name>
		<email>mj@gmail.com</email>
		<phone>5678901234</phone>
	</customer>
</customers>
