=== GargSheetal/computer-repair-servic/src/main/resources/repairshop/xmldata/customer_devices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="customer_devices">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="customer_device" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="serial_number" type="xs:string"/>
              <xs:element name="customer">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="last_name" type="xs:string"/>
                    <xs:element name="rest_of_name" type="xs:string"/>
                    <xs:element name="email" type="xs:string"/>
                    <xs:element name="phone" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="customer_id" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="device">
                <xs:complexType>
                  <xs:attribute name="device_id" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="customer_device_id" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== GargSheetal/computer-repair-servic/src/main/resources/repairservice/xmldata/customer_devices.xml
<?xml version="1.0" encoding="UTF-8"?>

<customer_devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="customer_devices.xsd">
	<customer_device customer_device_id="1">
		<serial_number>IPhone14-001</serial_number>
		<customer customer_id = "1">
			<last_name>Shelton</last_name>
			<rest_of_name>Mark</rest_of_name>
			<email>ms@gmail.com</email>
			<phone>2345645678</phone>
		</customer>
		<device device_id = "1"/>
	</customer_device>
</customer_devices>
