=== GargSheetal/computer-repair-servic/src/main/resources/repairshop/xmldata/device_types.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="device_types">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="device_type" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="device_type_name" type="xs:string"/>
              <xs:element name="device_brand">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="brand_name" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="device_brand_id" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="device_type_id" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== GargSheetal/computer-repair-servic/src/main/resources/repairshop/xmldata/device_types.xml
<?xml version="1.0" encoding="UTF-8"?>
<device_types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="device_types.xsd">
	<device_type device_type_id="1">
		<device_type_name>smartphone</device_type_name>
		<device_brand device_brand_id="1">
			<brand_name>Apple</brand_name>
		</device_brand>
	</device_type>
	<device_type device_type_id="2">
		<device_type_name>smartphone</device_type_name>
		<device_brand device_brand_id="2">
			<brand_name>Samsung</brand_name>
		</device_brand>
	</device_type>
	<device_type device_type_id="3">
		<device_type_name>smartphone</device_type_name>
		<device_brand device_brand_id="4">
			<brand_name>Google</brand_name>
		</device_brand>
	</device_type>
	<device_type device_type_id="4">
		<device_type_name>tablet</device_type_name>
		<device_brand device_brand_id="1">
			<brand_name>Apple</brand_name>
		</device_brand>
	</device_type>
	<device_type device_type_id="5">
		<device_type_name>tablet</device_type_name>
		<device_brand device_brand_id="2">
			<brand_name>Samsung</brand_name>
		</device_brand>
	</device_type>
</device_types>
