=== GargSheetal/computer-repair-servic/src/main/resources/repairshop/xmldata/work_requests.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="work_requests">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="work_request" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="work_type">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="work_description" type="xs:string"/>
                    <xs:element name="price" type="xs:decimal"/>
                    <xs:element name="device">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="device_name" type="xs:string"/>
                          <xs:element name="device_type">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="device_type_name" type="xs:string"/>
                                <xs:element name="device_brand">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="brand_name" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="device_brand_id" type="xs:integer" use="required"/>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="device_type_id" type="xs:integer" use="required"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="device_id" type="xs:integer" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="work_type_id" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="customer_device">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="serial_number" type="xs:string"/>
                    <xs:element name="customer">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="last_name" type="xs:string"/>
                          <xs:element name="rest_of_name" type="xs:string"/>
                          <xs:element name="email" type="xs:string"/>
                          <xs:element name="phone" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="customer_id" type="xs:integer" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="customer_device_id" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="created_timestamp" type="xs:dateTime"/>
              <xs:element name="last_updated_timestamp" type="xs:dateTime"/>
              <xs:element name="completed_timestamp" type="xs:dateTime"/>
              <xs:element name="amount" type="xs:decimal"/>
              <xs:element name="work_request_description" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="work_request_id" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== GargSheetal/computer-repair-servic/src/main/resources/repairshop/xmldata/work_requests.xml
<?xml version="1.0" encoding="UTF-8"?>

<work_requests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="work_requests.xsd">
	<work_request work_request_id="1">
		<work_type work_type_id="1">
			<work_description>Screen Replacement</work_description>
			<price>200.00</price>
			<device device_id="1">
				<device_name>iPhone 14</device_name>
				<device_type device_type_id="1">
					<device_type_name>smartphone</device_type_name>
					<device_brand device_brand_id="1">
						<brand_name>Apple</brand_name>
					</device_brand>
				</device_type>
			</device>
		</work_type>
		<customer_device customer_device_id="1">
			<serial_number>IPhone14-001</serial_number>
			<customer customer_id = "1">
				<last_name>Shelton</last_name>
				<rest_of_name>Mark</rest_of_name>
				<email>ms@gmail.com</email>
				<phone>2345645678</phone>
			</customer>
		</customer_device>
		<created_timestamp>2023-01-23T12:45:56</created_timestamp>
		<last_updated_timestamp>2023-01-25T14:30:40</last_updated_timestamp>
		<completed_timestamp>2023-01-27T11:15:26</completed_timestamp>
		<amount>200.00</amount>	
		<work_request_description>please do screen replacement for my iPhone14. Thanks Mark Shelton</work_request_description>
	</work_request>
</work_requests>
